improve sweep mechanism

diff --git a/build b/build
--- a/build
+++ b/build
@@ -14,6 +14,16 @@
 
 # ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
 
+# notes on some prerequisites
+#
+# Really we should check the prerequisites here.
+
+# 1. You need to have installed rust.
+# 2. You need to have run "cargo install cargo-sweep".
+# 3. You need to have run "cargo install cargo-license".
+
+# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
+
 # import and update enclone-data
 
 if ( !(-d enclone-data) ) then
@@ -84,16 +94,20 @@ git -C enclone-data write-tree --prefix=big_inputs/version15 > datasets_medium_c
 
 # sweep, to prevent target from becoming gigantic over time
 #
-# The cap is set at about 10 GB.
-#
-# Note that if this turns out to be too slow, we can restrict to running it periodically rather 
-# than on every invocation of build.
+# The cap is set at about 10 GB.  The sweep is run at most once per day.
 
-set start = `date +%s`
-cargo sweep --maxsize 10000 > /dev/null
-if ( $status != 0 ) then
-    echo "sweep failed, please try rerunning by hand"
+set start         = `date +%s`
+set last_sweep    = `cat stamps/last_sweep`
+set elapsed_sweep = `expr $start - $last_sweep`
+if ( $elapsed_sweep > 86400 ) then
+    cargo sweep --maxsize 10000 > /dev/null
+    if ( $status != 0 ) then
+        echo "sweep failed, please try rerunning by hand"
+        echo "or perhaps you need to \"cargo install cargo-sweep\""
+        exit 1
+    endif
+    set stop = `date +%s`
+    set sweep_time = `expr $stop - $start`
+    echo "sweep took $sweep_time seconds"
+    echo $stop > stamps/last_sweep
 endif
-set stop = `date +%s`
-set sweep_time = `expr $stop - $start`
-echo "sweep took $sweep_time seconds"
