./test now reports compilation time separately

diff --git a/test b/test
--- a/test
+++ b/test
@@ -41,6 +41,17 @@ if ( $elapsed_linktest > 86400 ) then
     echo $linkstart > stamps/last_linktest
 endif
 
+#### COMPILE FOR TEST SO WE CAN SEPARATELY TRACK COMPILE TIME ####
+
+set compile_start = `date +%s`
+cargo test --no-run >& /dev/null
+if ( $status != 0 ) then
+    echo "compilation failed, try cargo test --no-run
+    exit 1
+endif
+set compile_end = `date +%s`
+set compile_elapsed = `expr $compile_end - $compile_start`
+
 ##### GET START TIME #####
 
 set start = `date +%s`
@@ -94,6 +105,7 @@ set elapsed = `expr $end - $start`
 
 ##### FAIL IF TOO MUCH TIME USED #####
 
+echo "\ntest compile time = $compile_elapsed seconds"
 set expected = 171
 set fudge_num = 11
 set fudge_den = 10
@@ -108,7 +120,7 @@ if ( $elapsed_times > $expected_plus_times ) then
     echo
     exit 1
 else
-    echo "\ntotal test time = $elapsed seconds versus expected time of $expected seconds"
+    echo "total noncompile test time = $elapsed seconds versus expected time of $expected seconds"
 endif
 
 ##### DONE #####
