tweak

diff --git a/test b/test
--- a/test
+++ b/test
@@ -44,10 +44,21 @@ endif
 #### COMPILE FOR TEST SO WE CAN SEPARATELY TRACK COMPILE TIME ####
 
 set compile_start = `date +%s`
-cargo test --features cpu --no-run >& /dev/null
-cargo test --features linkless --no-run >& /dev/null
+
+cargo test --features cpu test_accounting --no-run >& /dev/null
 if ( $status != 0 ) then
-    echo "compilation failed, try cargo test --no-run
+    echo "compilation failed"
+    exit 1
+endif
+cargo test --bin traceback1 --test enclone_test1 --test enclone_test2 --test enclone_test3 \
+    --test enclone_test4 --test enclone_test_peak_mem --test test_com --no-run >& /dev/null
+if ( $status != 0 ) then
+    echo "compilation failed"
+    exit 1
+endif
+cargo test -p enclone_tail --lib --no-run >& /dev/null
+if ( $status != 0 ) then
+    echo "compilation failed"
     exit 1
 endif
 set compile_end = `date +%s`
