various changes (#227)
D GENES AND JUNCTION REGIONS
- detect VDDJ
- add ALIGNn, that exhibits a visual alignment for chain n (for each exact subclonotype) to the 
  donor V(D)J reference, picking the best D for heavy chains / TRB; there are also ALIGN_2NDn, 
  JALIGNn, and JALIGN_2NDn.
- add GROUP_VJ_REFNAME_HEAVY and GROUP_VDJ_REFNAME_HEAVY
- document opt_d,... and change name to. d1_name,...
- add d1_score and d2_score
- improve opt_d
- add notion of global variables
- add global variables d_inconsistent_% and d_inconsistent_n
- add filter D_INCONSISTENT to show only clonotypes having D gene assignment inconsistencies
- add filters D_NONE and D_SECOND
- add new page on site "D genes and junction regions"

CRATES
- update crates
- move initial processing into its own crate (weirdly this made the executable 2% larger)
- relax crate dependency restriction, so that enclone_core can depend on enclone_proto
- import a subset of rust-bio, with one modification

COMPUTATIONAL PERFORMANCE
- split some timers
- speed up doublet filtering and VDJ/GEX inconsistency testing

TESTING
- put all the tests that are affected by D region algorithms in their own test category
- ./test now fails if it used too much time
- move unaccounted time test prevent concurrence and remove from GitHub Actions
- don't warn about unused imports in tests

OTHER
- add a script that tags an enclone version corresponding to a given cellranger version
- add split-debuginfo = "unpacked" to Cargo.toml, because it speeds up Mac compilation
- add undocumented option TOOLTIP to add tooltip text to honeycomb plots
- landing pages now exhibits all help pages in a two-column (more compact) format
- add links to previous releases matching particular Cell Ranger versions
- fix bug in SUBSET_JSON
- add filter MAX_EXACTS

diff --git a/test b/test
--- a/test
+++ b/test
@@ -8,6 +8,10 @@
 # by .cargo/config.
 #
 # If you want to run this over and over to look for sporadic failures, use ./testtest.
+#
+# To run just one test,
+# cargo t <testname>
+# should work.
 
 ##### GET START TIME #####
 
@@ -20,9 +24,16 @@ if ( `where post_process_test` == "" ) then
     exit 1
 endif
 
-##### RUN TEST GROUP 1 #####
+##### RUN UNACCOUNTED TIME TEST #####
+
+# This is separate because we think it will fail less if it is not running at the same time
+# as other tests. Also, we don't want it in GitHub Actions because it fails occasionally.
 
 echo
+cargo test --features cpu test_accounting -- --nocapture |& post_process_test
+
+##### RUN TEST GROUP 1 #####
+
 cargo t |& post_process_test
 
 if ( $status != 0 ) then
@@ -43,5 +54,26 @@ endif
 
 set end = `date +%s`
 set elapsed = `expr $end - $start`
-echo "used $elapsed seconds total"
+
+##### FAIL IF TOO MUCH TIME USED #####
+
+set expected = 128
+set fudge_num = 11
+set fudge_den = 10
+set expected_plus_times = `expr $expected \* $fudge_num`
+set elapsed_times = `expr $elapsed \* $fudge_den`
+if ( $elapsed_times > $expected_plus_times ) then
+    echo "\nThe expected time for the test is $expected seconds, with an allowed fudge factor of"
+    echo "10%, but the test actually took $elapsed seconds.  If something has been done to make"
+    echo "the test actually slower, this is a real failure.  However it may be that the failure"
+    echo "is due simply to server load, or bad luck, and in that case it is not a failure."
+    echo "FAILED"
+    echo
+    exit 1
+else
+    echo "\ntotal test time = $elapsed seconds versus expected time of $expected seconds"
+endif
+
+##### DONE #####
+
 echo
