several changes (#200)
1. To determine assignment of chains to columns in a clonotype table, we now rely primarily on the column information implied by the original joins of exact subclonotypes.  This eliminates some artifactual behavior.  This is a major change to the algorithm, which is documented with new text
on the heuristics and history pages.
2. Change weak chain filtering to permit deletion of chains supported by up to 20 cells, rather 
   than 5.  This fixes some pathological cases involving clonotypes having many chains.
3. Add improved code for diffing the results of two versions of enclone.
4. Add option FOLD_HEADERS that causes the column headers to be folded, particularly useful
   if there are a crazy large number of chains.
5. Update hdf5 crate.
6. BUG FIXES
   (a) Fix bug in error handling that sometimes resulted in traceback after error message.
   (b) Add sanity check to make_ann_region.
   (c) Make LVAR= (with no value) work.
   (d) Fix a case where a feature function asserted if provided a sufficiently defective sequence.
7. TESTING
   (a) When a main test fails, show the comments for that test.
   (b) Improve ./test.
   (c) Add peak memory test.

diff --git a/test b/test
--- a/test
+++ b/test
@@ -12,8 +12,13 @@
 #
 # See also README.
 
-/usr/bin/time -f %E \
-    cargo t \
+##### GET START TIME #####
+
+set start = `date +%s`
+
+##### RUN TEST GROUP 1 #####
+
+cargo t \
     |& grep --line-buffered -v "^running" \
     | grep --line-buffered -v " Running "
 
@@ -22,8 +27,9 @@ if ( $status != 0 ) then
     exit 1
 endif
 
-/usr/bin/time -f %E \
-    cargo test -p enclone_tail --lib -- --nocapture \
+##### RUN TEST GROUP 2 #####
+
+cargo test -p enclone_tail --lib -- --nocapture \
     |& egrep -v "Finished|Running" | grep -v "^running"
 
 if ( $status != 0 ) then
@@ -31,4 +37,23 @@ if ( $status != 0 ) then
     exit 1
 endif
 
+##### RUN TEST GROUP 3 #####
+
+cargo test --manifest-path enclone_main/Cargo.toml --features mem -- --nocapture \
+    |& grep --line-buffered -v "^running" \
+    | grep --line-buffered -v " Running " \
+    | grep --line-buffered -v " Doc-tests " \
+    | grep --line-buffered -v " filtered out" \
+    | tr -s '\n'
+
+if ( $status != 0 ) then
+    echo "FAILED!"
+    exit 1
+endif
+
+##### REPORT TIME USED #####
+
+set end = `date +%s`
+set elapsed = `expr $end - $start`
+echo "used $elapsed seconds total"
 echo
