./test now fails if the test used too much time

diff --git a/test b/test
--- a/test
+++ b/test
@@ -44,4 +44,24 @@ endif
 set end = `date +%s`
 set elapsed = `expr $end - $start`
 echo "used $elapsed seconds total"
+
+##### FAIL IF TOO MUCH TIME USED #####
+
+set expected = 104
+set fudge_num = 11
+set fudge_den = 10
+set expected_plus_times = `expr $expected \* $fudge_num`
+set elapsed_times = `expr $elapsed \* $fudge_den`
+if ( $elapsed_times > $expected_plus_times ) then
+    echo "\nThe expected time for the test is $expected seconds, with an allowed fudge factor of"
+    echo "10%, but the test actually took $elapsed seconds.  If something has been done to make"
+    echo "the test actually slower, this is a real failure.  However it may be that the failure"
+    echo "is due simply to server load, or bad luck, and in that case it is not a failure."
+    echo "FAILED"
+    echo
+    exit 1
+endif
+
+##### DONE #####
+
 echo
